### ISSUE TITLE
html/template: no files named in call to ParseFiles

### ISSUE THREAD

**Issue by erikwoo** [mariomac/goblog#5]
```
# compose-example.yml
# docker compose -f compose-example.yml up
version: "3.8"

services:
  # Service to instrument. Change it to any
  # other container that you want to instrument.
  goblog:
    image: mariomac/goblog:dev
    ports:
      # Exposes port 18843, forwarding it to container port 8443
      - "18443:8443"

  autoinstrumenter:
    image: grafana/beyla:latest
    pid: "service:goblog"
    privileged: true
    environment:
      BEYLA_TRACE_PRINTER: text
      BEYLA_OPEN_PORT: 8443```yaml

# the goblog failed, with error:

```
beyla-goblog-1            | time=2024-09-29T10:35:01.861Z level=ERROR msg="can't start blog handler. ABORTING" error="loading resources: loading template: parsing template files: html/template: no files named in call to ParseFiles" rootPath=./ domain=localhost
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: can't get final child's PID from pipe: EOF: unknown
```sh

**Comment by mariomac** [comment]
Hi @erikwoo The Goblog container expects a configuration file/env vars and a mounted volume with the blog files. For example:
```yaml
  goblog:
    restart: unless-stopped
    image: docker.io/mariomac/goblog:dev
    environment:
      GOBLOG_ROOT: /contents
    volumes:
      - ./sample:/contents
``/
